#include <stdlib.h>
#include <string.h>
#include <stdint.h>

#include "list.h"

#pragma once
#ifdef __cplusplus
extern "C" {
#endif
typedef struct StringBuilder {
    size_t capacity;
        size_t size;
            char *text;
            } StringBuilder;

            StringBuilder *sb_new(const char *text) {
                StringBuilder *str = (StringBuilder *)malloc(sizeof(StringBuilder));

                    str->size = strlen(text);
                        str->capacity = (str->size + 1) * 2;
                            str->text = (char *)malloc(str->capacity);
                                memcpy(str->text, text, str->size + 1);
                                    return str;
                                    }

                                    StringBuilder *sb_copy(StringBuilder *str) {
                                        return sb_new(str->text);
                                        }

                                        StringBuilder *sb_trim_capacity(StringBuilder *str) {
                                            str->capacity = str->size;
                                                str->text = (char *)realloc(str->text, str->size);
                                                    return str;
                                                    }

                                                    StringBuilder *sb_resize(StringBuilder *str, size_t newSize) {
                                                        if (newSize >= str->capacity) {
                                                                str->capacity = (newSize + 1) * 2;
                                                                        str->text = (char *)realloc(str->text, str->capacity);
                                                                            }

                                                                                str->size = newSize;
                                                                                    return str;
                                                                                    }

                                                                                    StringBuilder *sb_set_text(StringBuilder *str, const char* newText) {
                                                                                        size_t newTextSize = strlen(newText);

                                                                                            if (newTextSize >= str->capacity) {
                                                                                                    str->capacity = (newTextSize + 1) * 2;
                                                                                                            str->text = (char *)malloc(str->capacity);
                                                                                                                }

                                                                                                                    str->size = newTextSize;
                                                                                                                        memcpy(str->text, newText, str->size + 1);
                                                                                                                            return str;
                                                                                                                            }

                                                                                                                            char sb_get(StringBuilder *str, const size_t index) {
                                                                                                                                return str->text[index % str->size];
                                                                                                                                }

                                                                                                                                StringBuilder *sb_set(StringBuilder *str, const size_t index, const char c) {
                                                                                                                                    str->text[index % str->size] = c;
                                                                                                                                        return str;
                                                                                                                                        }

                                                                                                                                        StringBuilder *sb_append(StringBuilder *str, const char *newText) {
                                                                                                                                            size_t newTextSize = strlen(newText);
                                                                                                                                                size_t oldSize = str->size;

                                                                                                                                                    sb_resize(str, str->size + newTextSize);
                                                                                                                                                        memcpy(str->text + oldSize, newText, newTextSize + 1);
                                                                                                                                                            return str;
                                                                                                                                                            }

                                                                                                                                                            int sb_equals(StringBuilder *str, const char* otherText) {
                                                                                                                                                                size_t otherTextSize = strlen(otherText);

                                                                                                                                                                    if (otherTextSize != str->size) {
                                                                                                                                                                            return 0;
                                                                                                                                                                                }

                                                                                                                                                                                    for (size_t i = 0; i < str->size; i++) {
                                                                                                                                                                                            if (str->text[i] != otherText[i]) {
                                                                                                                                                                                                        return 0;
                                                                                                                                                                                                                }
                                                                                                                                                                                                                    }

                                                                                                                                                                                                                        return 1;
                                                                                                                                                                                                                        }

                                                                                                                                                                                                                        int sb_starts_with(StringBuilder *str, const char *otherText, size_t offset) {
                                                                                                                                                                                                                            size_t otherTextSize = strlen(otherText);

                                                                                                                                                                                                                                if (offset + otherTextSize > str->size) {
                                                                                                                                                                                                                                        return 0;
                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                for (size_t i = 0; i < otherTextSize; i++) {
                                                                                                                                                                                                                                                        if (str->text[offset + i] != otherText[i]) {
                                                                                                                                                                                                                                                                    return 0;
                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                    return 1;
                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                    int64_t sb_index_of(StringBuilder *str, const char *substring) {
                                                                                                                                                                                                                                                                                        size_t substringSize = strlen(substring);

                                                                                                                                                                                                                                                                                            if (substringSize > str->size) {
                                                                                                                                                                                                                                                                                                    return -1;
                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                            size_t count = str->size - substringSize + 1;
                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                    for (size_t i = 0; i < count; i++) {
                                                                                                                                                                                                                                                                                                                            if (sb_starts_with(str, substring, i)) {
                                                                                                                                                                                                                                                                                                                                        return i;
                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                        return -1;
                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                        int64_t sb_last_index_of(StringBuilder *str, const char *substring) {
                                                                                                                                                                                                                                                                                                                                                            size_t substringSize = strlen(substring);

                                                                                                                                                                                                                                                                                                                                                                if (substringSize > str->size) {
                                                                                                                                                                                                                                                                                                                                                                        return -1;
                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                for (int64_t i = str->size - substringSize; i >= 0; i--) {
                                                                                                                                                                                                                                                                                                                                                                                        if (sb_starts_with(str, substring, i)) {
                                                                                                                                                                                                                                                                                                                                                                                                    return i;
                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                    return -1;
                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                    int sb_contains(StringBuilder *str, const char *substring) {
                                                                                                                                                                                                                                                                                                                                                                                                                        size_t count = str->size - strlen(substring) + 1;
                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                for (size_t i = 0; i < count; i++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                        if (sb_starts_with(str, substring, i)) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                    return 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Pass -1 for 'maxCount' to split to the end of the string
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    List *sb_split(StringBuilder *str, const char *value, int64_t maxCount) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        size_t valueSize = strlen(value);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            List *result = list_new(1024);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    list_append(result, sb_new(""));

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        size_t count = 0;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            for (size_t i = 0; i < str->size; i++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (sb_starts_with(str, value, i)) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (maxCount == -1 || count < maxCount) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                list_append(result, sb_new(""));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                i += valueSize - 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                count++;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                char temp[2] = { str->text[i], '\0' };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            sb_append(((StringBuilder **)result->data)[result->size - 1], temp);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return result;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            StringBuilder *sb_replace(StringBuilder *str, const char *a, const char *b) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                size_t aSkip = strlen(a) - 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    StringBuilder *tempStr = sb_new("");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        for (size_t i = 0; i < str->size; i++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (!sb_starts_with(str, a, i)) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            char temp[2] = { str->text[i], '\0' };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        sb_append(tempStr, temp);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            sb_append(tempStr, b);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        i += aSkip;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        free(str->text);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            str->text = tempStr->text;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                str->capacity = tempStr->capacity;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    str->size = tempStr->size;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        free(tempStr);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return str;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            StringBuilder *sb_remove(StringBuilder *str, const char* text) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return sb_replace(str, text, "");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                StringBuilder *sb_remove_index(StringBuilder *str, size_t index) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    for (size_t i = index + 1; i < str->size + 1; i++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            str->text[i - 1] = str->text[i]; 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    str->size -= 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return str;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        StringBuilder *sb_trim(StringBuilder *str, char c) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            while (str->text[0] == c) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    sb_remove_index(str, 0);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            while (str->text[str->size - 1] == c) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    sb_remove_index(str, str->size - 1);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return str;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            StringBuilder *sb_reverse(StringBuilder *str) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                for (size_t i = 0; i < str->size / 2; i++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const char temp = str->text[i];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                str->text[i] = str->text[str->size - i - 1];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        str->text[str->size - i - 1] = temp;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return str;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                StringBuilder *sb_clear(StringBuilder *str) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    str->text[0] = '\0';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        str->size = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return str;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            void sb_free(StringBuilder **str) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                free((*str)->text);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    free(*str);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        *str = NULL;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        #ifdef __cplusplus
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        #endif